[supabase]
url = "https://fuzjzcdnuhxompbmazrf.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1emp6Y2RudWh4b21wYm1henJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NDIyODEsImV4cCI6MjA1MTExODI4MX0.dyi15vuCcyl80yT5D5SnaITSJ6Rm35ILcwWWMlQZLBE"

[google]
key = "AIzaSyDO4Jy1s_pTxg9y6qEFZNMfnPPYfmJ6A98"